language: ruby
rvm:
  - 2.5.1
before_script:
  - gem install bundler-audit
script:
  # - bundle exec rspec --format documentation
  - bundle exec db:migrate RAILS_ENV=test
  - bundle exec rails test
  # - bundle exec rubocop --config .rubocop.yml
  # - bundle-audit check --update